### ISSUE TITLE
JSON.parse on `.data` will throw, `data` is a `buffer`

### ISSUE THREAD

**Issue by diasdavid** [haadcode/ipfs-log#93]
.data inside a IPFS object is a Buffer, so doing a straight JSON.parse will fail (or should)

https://github.com/haadcode/ipfs-log/blob/master/src/log.js#L120-L128

Since this JSON.parse is wrapped in a promise and there is no catch, the error goes in silence.

Another issue is that since logData might go undefined, logData.items will throw and error too.

**Comment by haadcode** [comment]
Thanks for diving into the depths of the code! :) However, what you describe here is not how the code works in that part.

> .data inside a IPFS object is a Buffer, so doing a straight JSON.parse will fail (or should)

JSON.parse can handle json-stringified Buffers and Arrays just fine.

> Since this JSON.parse is wrapped in a promise and there is no catch, the error goes in silence.

The responsibility to catch errors is on the consuming side:
```javascript
Log.fromIpfsHash(ipfs, "Qm...Foo")
  .then((res) => /* success */)
  .catch((e) => console.error(e))
```

This catches the errors `fromIpfsHash` can throw as well as the errors from the JSON.parse. It also catches assertion errors. The promises are chained, so the errors bubble up to the consumer.

> Another issue is that since logData might go undefined, logData.items will throw and error too.

Not true. Because JSON.parse will throw, in case of error the execution of the promises chain will stop before `logData` is used. Furthermore, even if `logData` was undefined, again, the promises chain would throw an assertion error.

Closing the issue as what is reported is simply incorrect.
