### ISSUE TITLE
Make the log data structure immutable

### ISSUE THREAD

**Issue by haadcode** [haadcode/ipfs-log#97]
Since day 1 I've been wanting to try the log as an immutable data structure instead of being an object that mutates its state. I believe this would make it easier to reason about the log as a *data structure*.

In practice, it would mean instead of:
```javascript
// log1: [1]
// log2: [2]
log1.join(log2).then((log) => /* log === log1, join mutates the instance */)
// log1: [1,2]
// log2: [2]
// log: [1,2]
```

We would write:
```javascript
// log1: [1]
// log2: [2]
log1.join(log2).then((log) => /* log !== log1, log1 hasn't changed */)
// or
Log.join(log1, log2).then((log) => /* log !== log1, log1 hasn't changed */)
// log1: [1]
// log2: [2]
// log: [1,2]
```

And soon:
```javascript
const log = await Log.join(log1, log2)
```

**Comment by haadcode** [comment]
And the full API would be something like:

```javascript
const Log = require('ipfs-log')

// need ipfs
const IPFS = require('ipfs')
const ipfs = new IPFS()

// create empty logs
// for the sake of example, using 'let' here
let log1 = new Log(ipfs)
let log2 = new Log(ipfs)

// add entries
log1 = Log.add(log1, 1)
log2 = Log.add(log2, 2)

console.log(log1.items)
// [{ value: 1, ... }]

console.log(log2.items)
// [{ value: 2, ... }]

// serialize
const hash1 = await Log.toIpfs(log1) // 'Qm...Foo1'
const hash2 = await Log.toIpfs(log2) // 'Qm...Foo2'

// deserialize
const logA = await Log.from('Qm...Foo1')
const logB = await Log.from('Qm...Foo2')

// merge
const log = await Log.join(logA, logB)

console.log(log.items)
// [{ value: 1, ... }, { value: 2, ... }]
```

**Comment by haadcode** [comment]
cc @keks what are your thoughts on this?

**Comment by keks** [comment]
Hmm, I'm not sure what the benefit is. I'll comment on each argument inline.

> Operations on a log always return a new instance

How is that good? Seems like the code would just get more verbose and noisy.

> Operations on a log become pure functions

Seems very similar to the previous argument. I don't know, maybe this makes sense in JS because it has many functional influences, but doing stuff like that in Go wouldn't work, just like procedural Haskell wouldn't work well either.

> Functions with side effects can be abstracted to a very thin layer on top of an interface that implements the operations.

Isn't that the case in the Go implementation? There is the "immutabledb" interface and the corresponding IPFS driver. Or do you mean something else?

> Allows fetching a full log in parts (partial join and expand)

I really like the idea, but we could do that without making all of the API pure, right?

> Log size can be controlled on IO and memory level

I think this is a side-effect (huh) of expand so the same applies

> Logs become "snapshots in time"

Again, I don't see the benefit. You can today do a query "give me all entries up to entry x" and the result will always be the same, i.e. a snapshot.

Let's keep the discussion going! I also have an idea I want to write up. Maybe I can make it this weekend.

**Comment by haadcode** [comment]
Worked on this over the holidays. Almost finished version here: https://github.com/haadcode/ipfs-log/commit/c96e01d1638df6ca534f98e8256a31bace2a96e9.

Gotta say, I like the immutable version quite a bit more :)

@keks I'll get back to you your comments but quickly: if functional/immutable approach doesn't work in Go, there's no reason to have the implementations match. If OO is better / more idiomatic, then go for that. This issue wasn't meant to find a one-solution-to-rule-them-all, but rather I wanted to see how this could be turned into immutable in JS.

**Comment by haadcode** [comment]
Working on to finish this for (js) ipfs-log in the next couple of days, PR here https://github.com/haadcode/ipfs-log/pull/100.
